#!/bin/bash
git fetch -p
BRANCHES=$(git for-each-ref --format '%(refname) %(upstream:track)' refs/heads | awk '$2 == "[gone]" {sub("refs/heads/", "", $1); print $1}')

echo cleaning up $BRANCHES
for branch in $BRANCHES; do
    git branch -D $branch;
done